export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";
export const ERROR = "ERROR";
export const ORDER_START_LOADING = "ORDER_START_LOADING";
export const ORDER_END_LOADING = "ORDER_END_LOADING";
export const FETCH_ORDERS_END_LOADING = "FETCH_ORDERS_END_LOADING";
export const FETCH_ORDERS_START_LOADING = "FETCH_ORDERS_START_LOADING";
export const FETCH_ORDERS = "FETCH_ORDERS";
